#ifndef INPUT_H
#define INPUT_H

#include "core.h"

#define INPUT_DEBOUNCE_FRAMES 2

#define ANALOGS_DEADZONE 1

void input_init();
void input_read_and_run_callbacks();


#define INPUT_DECLARE_BUTTON_SETTER(BUTTON) \
    void input_set_callback_ ## BUTTON(void(*callback)(void))

#define INPUT_DECLARE_ANALOG_SETTER(STICK) \
    void input_set_callback_analog_ ## STICK(void(*callback)(unsigned char,unsigned char))


INPUT_DECLARE_BUTTON_SETTER(up);
INPUT_DECLARE_BUTTON_SETTER(right);
INPUT_DECLARE_BUTTON_SETTER(down);
INPUT_DECLARE_BUTTON_SETTER(left);

INPUT_DECLARE_BUTTON_SETTER(triangle);
INPUT_DECLARE_BUTTON_SETTER(circle);
INPUT_DECLARE_BUTTON_SETTER(cross);
INPUT_DECLARE_BUTTON_SETTER(square);

INPUT_DECLARE_BUTTON_SETTER(l1);
INPUT_DECLARE_BUTTON_SETTER(l2);
INPUT_DECLARE_BUTTON_SETTER(l3);
INPUT_DECLARE_BUTTON_SETTER(r1);
INPUT_DECLARE_BUTTON_SETTER(r2);
INPUT_DECLARE_BUTTON_SETTER(r3);

INPUT_DECLARE_BUTTON_SETTER(select);
INPUT_DECLARE_BUTTON_SETTER(start);

INPUT_DECLARE_ANALOG_SETTER(left);
INPUT_DECLARE_ANALOG_SETTER(right);


#endif